### ISSUE TITLE
HI /anvil  ... use ESC item will disappear

### ISSUE THREAD

**Issue by tygh78071388** [ExplosiveMine/Anvil#3]
video https://youtu.be/YYVt3oNwSuM

PLS fix

3162-Spigot-f773da8-b121d3b (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
Anvil v1.2.1

**Comment by ExplosiveMine** [comment]
noted

**Comment by ExplosiveMine** [comment]
fixed
